import datetime
import os
import yfinance as yf
import pandas as pd
import requests

WATCHLIST = ["AAPL", "NVDA", "MSFT", "TSLA", "META", "AMZN", "GOOGL", "SPY"]
TODAY = datetime.date.today()


def fetch(symbol: str) -> dict | None:
    try:
        t = yf.Ticker(symbol)
        hist = t.history(period="1y")
        if hist.empty:
            return None
        if hasattr(hist.index, "tz") and hist.index.tz is not None:
            hist.index = hist.index.tz_convert(None)

        close = hist["Close"]
        volume = hist["Volume"]
        c = float(close.iloc[-1])
        prev = float(close.iloc[-2])
        chg = round((c - prev) / prev * 100, 2)

        sma50 = float(close.rolling(50).mean().iloc[-1])
        sma200 = float(close.rolling(200).mean().iloc[-1])
        high52 = float(close.rolling(252).max().iloc[-1])
        low52 = float(close.rolling(252).min().iloc[-1])

        delta = close.diff()
        gain = delta.clip(lower=0).rolling(14).mean()
        loss = (-delta.clip(upper=0)).rolling(14).mean()
        rs = gain / loss.replace(0, float("nan"))
        rsi = round(float((100 - 100 / (1 + rs)).iloc[-1]), 1)

        ema12 = close.ewm(span=12, adjust=False).mean()
        ema26 = close.ewm(span=26, adjust=False).mean()
        macd_line = ema12 - ema26
        signal = macd_line.ewm(span=9, adjust=False).mean()
        macd_hist = float((macd_line - signal).iloc[-1])

        vol_avg = float(volume.rolling(20).mean().iloc[-1])
        vol_ratio = round(float(volume.iloc[-1]) / vol_avg, 2) if vol_avg > 0 else 1.0

        above_50 = c > sma50
        above_200 = c > sma200
        near_high = c >= high52 * 0.85
        trend_score = sum([above_50, above_200, near_high, c >= low52 * 1.25, sma50 > sma200])

        rsi_signal = "Overbought" if rsi > 70 else "Oversold" if rsi < 30 else "Neutral"
        macd_signal = "Bullish" if macd_hist > 0 else "Bearish"

        score = 50
        score += 15 if above_50 and above_200 else -10
        score += 10 if near_high else -5
        score += 10 if macd_hist > 0 else -10
        score += 5 if 40 < rsi < 65 else (-10 if rsi > 75 else 0)
        score += 5 if vol_ratio > 1.2 else 0
        score = max(0, min(100, score))

        grade = "A" if score >= 80 else "B" if score >= 65 else "C" if score >= 50 else "D" if score >= 35 else "F"

        info = {}
        try:
            info = t.fast_info
        except Exception:
            pass

        return {
            "symbol": symbol,
            "price": round(c, 2),
            "chg_pct": chg,
            "sma50": round(sma50, 2),
            "sma200": round(sma200, 2),
            "high52": round(high52, 2),
            "low52": round(low52, 2),
            "rsi": rsi,
            "rsi_signal": rsi_signal,
            "macd_signal": macd_signal,
            "vol_ratio": vol_ratio,
            "trend_score": trend_score,
            "score": score,
            "grade": grade,
            "above_50": above_50,
            "above_200": above_200,
        }
    except Exception as e:
        print(f"[{symbol}] error: {e}")
        return None


def vix() -> float:
    try:
        v = yf.Ticker("^VIX").history(period="5d")
        return round(float(v["Close"].iloc[-1]), 2)
    except Exception:
        return 20.0


def market_status(spy: dict, vix_val: float) -> str:
    if spy is None:
        return "UNKNOWN"
    if spy["above_50"] and spy["above_200"] and vix_val < 20:
        return "CONFIRMED UPTREND ✅"
    elif spy["above_50"] and vix_val < 28:
        return "UPTREND UNDER PRESSURE ⚠️"
    else:
        return "CORRECTION 🔴"


def grade_emoji(g: str) -> str:
    return {"A": "🟢", "B": "🔵", "C": "🟡", "D": "🟠", "F": "🔴"}.get(g, "⚪")


def build_report(assets: list[dict], vix_val: float) -> str:
    spy = next((a for a in assets if a["symbol"] == "SPY"), None)
    status = market_status(spy, vix_val)
    sorted_assets = sorted([a for a in assets if a["symbol"] != "SPY"], key=lambda x: x["score"], reverse=True)

    lines = [
        f"# 📊 Market Intelligence Report — {TODAY}",
        "",
        "> Generated by FinancialMarket_Intelbot | Live data via yfinance",
        "",
        "---",
        "",
        "## 1. Market Snapshot",
        "",
        f"| Indicator | Value |",
        f"|-----------|-------|",
        f"| VIX | {vix_val} |",
        f"| VIX Regime | {'⚠️ Elevated' if vix_val > 25 else '🟢 Normal' if vix_val < 18 else '🟡 Moderate'} |",
        f"| SPY Price | ${spy['price'] if spy else 'N/A'} |",
        f"| SPY Change | {spy['chg_pct']:+.2f}% |" if spy else "| SPY Change | N/A |",
        f"| SPY vs SMA50 | {'Above ✅' if spy and spy['above_50'] else 'Below ❌'} |",
        f"| SPY vs SMA200 | {'Above ✅' if spy and spy['above_200'] else 'Below ❌'} |",
        f"| **Market Status** | **{status}** |",
        "",
        "---",
        "",
        "## 2. Asset Scores",
        "",
        "| Symbol | Price | Change | RSI | MACD | Vol Ratio | Trend | Score | Grade |",
        "|--------|-------|--------|-----|------|-----------|-------|-------|-------|",
    ]

    for a in sorted_assets:
        chg_str = f"{a['chg_pct']:+.2f}%"
        lines.append(
            f"| {a['symbol']} | ${a['price']} | {chg_str} | {a['rsi']} ({a['rsi_signal']}) "
            f"| {a['macd_signal']} | {a['vol_ratio']}x | {a['trend_score']}/5 "
            f"| {a['score']} | {grade_emoji(a['grade'])} **{a['grade']}** |"
        )

    lines += [
        "",
        "---",
        "",
        "## 3. Deep Analysis",
        "",
    ]

    for a in sorted_assets:
        pct_from_high = round((a["price"] - a["high52"]) / a["high52"] * 100, 1)
        pct_from_low = round((a["price"] - a["low52"]) / a["low52"] * 100, 1)
        lines += [
            f"### {grade_emoji(a['grade'])} {a['symbol']} — Grade {a['grade']} ({a['score']}/100)",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Price | ${a['price']} ({a['chg_pct']:+.2f}% today) |",
            f"| 52-Week Range | ${a['low52']} — ${a['high52']} |",
            f"| From 52W High | {pct_from_high:+.1f}% |",
            f"| From 52W Low | +{pct_from_low:.1f}% |",
            f"| SMA(50) | ${a['sma50']} ({'Above' if a['above_50'] else 'Below'}) |",
            f"| SMA(200) | ${a['sma200']} ({'Above' if a['above_200'] else 'Below'}) |",
            f"| RSI(14) | {a['rsi']} — {a['rsi_signal']} |",
            f"| MACD | {a['macd_signal']} |",
            f"| Volume Ratio | {a['vol_ratio']}x avg |",
            f"| Trend Template | {a['trend_score']}/5 criteria |",
            "",
        ]

    lines += [
        "---",
        "",
        "## 4. Ranked Watchlist",
        "",
    ]
    for i, a in enumerate(sorted_assets, 1):
        action = "Watch for entry" if a["grade"] in ("A", "B") and a["above_50"] else "Avoid" if a["grade"] == "F" else "Hold / Monitor"
        lines.append(f"{i}. **{a['symbol']}** — {grade_emoji(a['grade'])} {a['grade']} ({a['score']}/100) — {action}")

    lines += [
        "",
        "---",
        "",
        f"*Report generated {TODAY} | FinancialMarket_Intelbot | Data: yfinance*",
    ]

    return "\n".join(lines)


def main():
    print(f"[FinBot] Generating report for {TODAY}...")
    vix_val = vix()
    print(f"[FinBot] VIX: {vix_val}")

    assets = []
    for sym in WATCHLIST:
        print(f"[FinBot] Fetching {sym}...")
        data = fetch(sym)
        if data:
            assets.append(data)

    if not assets:
        print("[FinBot] No data fetched — aborting")
        return

    report = build_report(assets, vix_val)
    os.makedirs("reports", exist_ok=True)
    path = f"reports/{TODAY}.md"
    with open(path, "w") as f:
        f.write(report)
    print(f"[FinBot] Report saved → {path}")


if __name__ == "__main__":
    main()
